trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - azure-pipelines.yml

variables:
- group: Robilityflowgroup

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      displayName: 'Clone GitHub and Push to Azure DevOps'
      inputs:
        script: |
          echo "Cloning GitHub repo..."
          git clone https://github.com/YogaSutherland/robility.git
          cd robility

          echo "Configuring Git credentials..."
          git config user.email $(GithubEmail)
          git config user.name $(YogaSutherland)

          echo "Adding Azure DevOps remote..."
          git remote add azure $(AZURE_DEVOPS_URL)

          echo "Pushing code to Azure DevOps..."
          git push azure main --force